### ISSUE TITLE
Extension doesn't load in Fedora 30 (Gnome Shell 3.32)

### ISSUE THREAD

**Issue by jlfranklin** [bo32/gnome-shell-extension-duolingo-status#10]
May only need updated metadata, may need some code changes.

**Comment by bo32** [comment]
Hi, I haven't had time to finish migrating to the new version of gnome-shell. I'm planning on finishing it next week - I'll post here when done.

**Comment by bo32** [comment]
please check the master branch for latest updates and fixes.
I'll post the new version on the Gnome Shell Extensions website in a few minutes.

**Comment by Emil-Wozniak** [comment]
That could be fix if you disable and enable add-on, after write down you credentials.
