### ISSUE TITLE
Installation error and connection failure

### ISSUE THREAD

**Issue by tyrandus** [bo32/gnome-shell-extension-duolingo-status#12]
Currently, the installation from the GNOME extensions web page returns an error. I had the app installed but it regularly gave me a connection error so I tried to reinstall — without success. Is the extension still maintained? I really enjoyed its functionality and would be glad to have it working again.

**Comment by bo32** [comment]
* what is your version of Gnome Shell ?
* do you still see the little Duolingo icon in your menu bar, in spite of the error? If yes, can you try to refresh (via the little refresh button next to the Duolingo link)?

**Comment by tyrandus** [comment]
* I am running GNOME Shell 3.28.4 on a Ubuntu 18.04.
* I uninstalled the app because refreshing failed. It returned connection errors over a time span of several weeks. My hope was that a clean reinstall would fix this issue, however, downloading the app again was impossible as described above.

**Comment by bo32** [comment]
I would suggest that you upgrade to the latest version of gnome-shell,  3.3*. 
(the latest non LTS Ubuntu 19.04 embeds the latest version of gnome-shell : https://www.omgubuntu.co.uk/2018/11/ubuntu-19-04-release-features). There were quite some breaking changes when that new version was released, so I upgraded my extension to support these (not guaranting the retro compatibility).

**Comment by tyrandus** [comment]
Alright, thank you for your support.
