### ISSUE TITLE
Icon position on topbar

### ISSUE THREAD

**Issue by arrufat** [bo32/gnome-shell-extension-duolingo-status#2]
Could you please add a setting for icon position in the topbar?

It could be something like this:
https://github.com/chrisss404/gnome-shell-ext-SkypeNotification/commit/15298bd6286d1f346e72735c5a9b21bdd54ac0ba

Thank you!

**Comment by bo32** [comment]
Hi, sure thanks for the proposition.
So basically you want to be able to hide the icon in the top right corner and display it in the tray icons?

**Comment by arrufat** [comment]
Well, I would like to be able to choose were in the panel the icon appears:
Before the system icons, after, after the layout button, etc
Thanks :)

**Comment by bo32** [comment]
Hi arrufat, sorry for the time it took.
Please check out the latest changes I have done and have a look at the option **Index icon position** and **Corner icon position** in the tab **Icon** in the preferences menu. Let me know if it's what you wanted :)

**Comment by arrufat** [comment]
Thank you very much! That is exactly what I wanted :D
