### ISSUE TITLE
not work in china

### ISSUE THREAD

**Issue by wyattjee** [bo32/gnome-shell-extension-duolingo-status#3]
I live in China, When I go to "duolingo.com", it will become "duolingo.cn", this shell extension not works when I use local network, it only shows 3 elements, ("Duolingo.com" strings with green color, a refresh icon, setting icon), but it works great when I connected to America's VPN, it shows the detail.

**Comment by bo32** [comment]
Hmmm... I don't know if it's some chinese restrictions or what... I'll investigate on it...

**Comment by bo32** [comment]
I don't know, maybe according to the location, some people in China cannot reach Duolingo. There are quite a few topics about it online... 
On this one, there is an email address to contact for China: https://www.duolingo.com/comment/2943539
Feel free to contact them. I will try to contact them too but not before next week, I don't have so much time currently.
Also, maybe try a trick (not sure it works at all). In the duolingo.js file (of the latest version of the project on Github), line 28, can you try to replace duolingo.com by duolingo.cn? If it works well, I'll implement a more generic way.

**Comment by wyattjee** [comment]
thanks, I solve it, I just add "www", and it works

> let url = 'https://www.duolingo.com/users/' + this.login;

**Comment by bo32** [comment]
ok, good to know! I'll try to make an update for this as soon as I can. Thanks for the resolution.
