### ISSUE TITLE
Missing flag for Japanese

### ISSUE THREAD

**Issue by jlfranklin** [bo32/gnome-shell-extension-duolingo-status#4]
Japanese for English speakers will be in beta later this month.  The flag of Japan is missing from the extension.  Can you add it, please?

**Comment by bo32** [comment]
Done.
Thanks for the notification :)

**Comment by bo32** [comment]
And the new version with the Japanese flag in validation process on the gnome-shell extensions website.

**Comment by jlfranklin** [comment]
Thank you!
